apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelines-controller
  namespace: tekton-pipelines
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/ztidp-dev-tekton-irsa
  labels:
    app.kubernetes.io/name: tekton-pipelines-controller
    team: platform
    cost-center: CC-PLATFORM-000
    environment: production
    owner: platform-team
