apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: github-binding
    team: platform
    cost-center: CC-PLATFORM-000
    environment: production
    owner: platform-team
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.ref)
    - name: commit-sha
      value: $(body.after)
