apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
  namespace: istio-system
  labels:
    app.kubernetes.io/name: backstage-tls
    team: platform
    cost-center: CC-PLATFORM-000
    environment: production
    owner: platform-team
spec:
  secretName: backstage-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - portal.idp.example.com
    - portal.dev.idp.example.com
    - portal.staging.idp.example.com
