apiVersion: v1
kind: Service
metadata:
  name: ${{ values.service_name }}
  namespace: ${{ values.team_name }}
  labels:
    app.kubernetes.io/name: ${{ values.service_name }}
    team: ${{ values.team_name }}
    cost-center: CC-${{ values.team_name | replace("-", "") | upper }}-001
    environment: dev
    owner: ${{ values.team_name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ${{ values.service_name }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
